project_name: 'opmd-binary-classification'

# dataset details
train_dir: '/ssd_scratch/cvit/chocolite/OPMD-Classification/train/'
val_dir: '/ssd_scratch/cvit/chocolite/OPMD-Classification/val/'
test_dir: '/ssd_scratch/cvit/chocolite/OPMD-Classification/test/'

seed: 42

# training details
init_lr: 0.0001
n_epochs: 50
batch_size: 32
num_workers: 24

data_aug: 0

# saving checkpoints
save_dir: '/ssd_scratch/cvit/chocolite/OPMD-Classification/weights/'
save_freq: 1

fold: 'x'
num_classes: 1

resize: 224

# model details
model: 
  name: 'densenet201'
  n_channels: 3

