project_name: 'opmd-binary-classification'

# dataset details
dataset:
  train_csv_path: 'data/opmd_train_foldx.csv'
  train_dir: '/ssd_scratch/cvit/chocolite/'

  val_csv_path: 'data/opmd_val_foldx.csv'
  val_dir: '/ssd_scratch/cvit/chocolite/'

  test_csv_path: 'data/opmd_test_foldx.csv'
  test_dir: '/ssd_scratch/cvit/chocolite/'

seed: 42

# training details
init_lr: 0.0001
n_epochs: 50
batch_size: 32
num_workers: 24

# 1: tr: img, te: img; 2: tr: img, te: segimg; 3: tr: segimg, te: segimg
setting: 1
# 1: segmentation on grayscale; 3: segmentation on RGB
seg_type: 3

data_aug: 1

# saving checkpoints
save_dir: '/ssd_scratch/cvit/chocolite/OPMD-GraceClassification/weights/'
save_freq: 1

fold: 1
num_classes: 1

resize: 256
crop: 224

# model details
model: 
  name: 'densenet201'
  n_channels: 3

quantize: True